# Generated by Django 4.1.5 on 2023-01-11 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, default='None', max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='colorvariant',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.brand'),
        ),
        migrations.AddField(
            model_name='sizevariant',
            name='brand',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='Product.brand'),
        ),
    ]
