# Generated by Django 4.1.5 on 2023-01-11 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_brand_colorvariant_brand_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariant',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Product.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Product.brand'),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Product.brand'),
        ),
    ]
