# Generated by Django 4.1.5 on 2023-01-14 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default='nothing', on_delete=django.db.models.deletion.DO_NOTHING, to='Product.brand'),
        ),
    ]
