# Generated by Django 4.1.5 on 2023-01-12 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_coupon_product_discount'),
        ('ECommerceAuth', '0008_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.coupon'),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
