# Generated by Django 4.1.5 on 2023-01-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerceAuth', '0009_alter_cart_coupon_delete_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
